### ISSUE TITLE
Error on PHPCR Admin Bundle

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/RoutingBundle#296]
I get the following error after when trying to use the Routing bundle with PHPCR Admin Bundle

PHP Fatal error:  Declaration of Symfony\Cmf\Bundle\RoutingBundle\Admin\RouteAdmin::validate() must be compatible with Sonata\AdminBundle\Admin\AdminInterface::validate(Sonata\CoreBundle\Validator\ErrorElement $errorElement, $object) in /home/ha/public_html/vendor/symfony-cmf/routing-bundle/Admin/RouteAdmin.php on line 25

        "symfony-cmf/routing-bundle": "1.4.*@dev",
        "sonata-project/doctrine-phpcr-admin-bundle": "2.0.*@dev"

**Comment by dbu** [comment]
these requirements give you development versions of the bundles. if you want something works without surprises, we recommend to declare a stable dependency instead of the latest dev version. in this instance, the reason is a BC break between sonata-project/admin-bundle 1.3 and 1.4 . there is #292 to fix this, which was just completed and merged.

so things should work now, but they might break occasionally again until things become stable.

**Comment by WouterJ** [comment]
Closing as bug is fixed
